
function [opt_prob, J, E_out] = wgconv(omega)

    modes(1) = model_I(omega, io(1, 'te0', 1), ...
                            {io(2, 'te0', [0.9 1])});
%     modes(2) = struct('omega', omega, ...
%                     'in', wg(1, 11, 'x+', 4), ...
%                     'out', [wg([0 delta], 69, 'x+', 4)], ...
%                     's_prim', {s_prim}, ...
%                     's_dual', {s_dual}, ...
%                     'mu', {mu}, ...
%                     'epsilon_const', {epsilon}, ...
%                     'S', (eps_hi - eps_lo) * S);


    %% Translate
    [opt_prob, J, E_out] = translation_layer(modes, @solve_local);
    % test_opt_prob(opt_prob, S); % Use to test opt_prob.
